{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "foodui.serviceAccountName" . }}
  labels:
{{ include "foodui.labels" . | nindent 4 }}
{{- end -}}
